MODEL:
  INPUT_SIZE: 224
TRAIN:
  EPOCH: 700
  BATCH_SIZE: 8
  LEARNING_RATE: 1.0e-4
  NUM_LAYERS: 16
  PRETRAINED: True
  DEVICE: "cpu"
  DATA_DIR: "/content/transistor"
  SAVE_DIR: "/content"
  CHECKPOINT_PATH: "/home/pep/Drive/PCLOUD/Projects/Anomaly-Detection/DFR/checkpoints/screw-epoch=400-auroc_score=0.98.pt"